package com.example.petadoption


import androidx.annotation.DrawableRes

data class Puppy(
    @DrawableRes val resId: Int,
    val name: String,
    val gender:String,
    val description: String
)

object PetsDetails {
    val puppies = listOf<Puppy>(
        Puppy(R.drawable.buster, "Buster","Female", "Buster was a dog belonging to Roy Hattersley, a British politician and former Deputy Leader of the Labour Party.Buster was a mongrel, as his father was a German Shepherd, and his mother a Staffordshire Bull Terrier. He was a former rescue dog adopted by Hattersley from Brent Animal Shelter, in 1995.In 1996, Buster attacked and killed a goose in St. James's Park, London. On 6 April, Hattersley was stopped and questioned by the police while returning home after walking Buster in the park. Buster was suspected of killing the goose, while not under Hattersley's control, and a quick check revealed blood around his muzzle. As the goose was located in a Royal Park, it was the property of The Queen. The Royal connection, coupled with Hattersley's prominent public position, led to national media coverage of the incident. He was charged with contravening Regulation 3(5)(b) of the Royal and Other Parks and Gardens Regulations 1977. On 20 November 1996, Hattersley pleaded guilty by letter, and was fined £25 for letting Buster off the lead (although he claimed that Buster had pulled the lead out of his hand), and £50 for letting him kill the goose."),
        Puppy(R.drawable.catnew, "Kitty", "Female","The American Wirehair is a spontaneous mutation of the American Shorthair. It first occurred as a random mutation among a litter of five born to a pair of barn cats in 1966 in Vernon, in upstate New York. This single red-and-white male had wiry fur. The owner of the cats called a local breeder of Rex cats, Mrs. Joan O'Shea, to take a look at the kitten. She bought the kitten for \$50, along with one of his normal-coated female littermates, to start a breeding program. The wirehaired male was named Council Rock Farms Adams of Hi-Fi ('Adam' for short),and the female Tip-Top."),
        Puppy(R.drawable.dog1, "Hula", "Female","The Shih Tzu is a strong little dog with a small muzzle and normally have large dark brown eyes. They have a soft and long double coat. Although sometimes long, a Shih Tzu will not always have extremely lengthy hair like the Pekingese (but with short legs). Some of them have more short, curly hair. This is purely a choice made by the owners. A Shih Tzu should stand no more than 26.7 cm at the withers and with an ideal weight of 4.0 to 7.5 kg. Floppy ears are covered with long fur, and the heavily furred tail is carried curled over the back. The coat may be of any color, though white and with blazes of grey are frequently seen."),
        Puppy(R.drawable.jack, "Jack", "Male","The American Bully, as it is now known, began development in the 1980s with the majority of the final behavioral and aesthetic product being completed in the 1990’s.[citation needed] There is consensus that at least five other breeds were used to attain the more \"bully\" physical traits desired as well as the more diminutive size of some lines. The American Pit Bull Terrier (APBT) was the foundation (parent breed) used to create the American Bully. The APBT has maintained a characteristic appearance and temperament for over a century."),
        Puppy(R.drawable.buster, "Buster", "Male","Buster was a dog belonging to Roy Hattersley, a British politician and former Deputy Leader of the Labour Party.Buster was a mongrel, as his father was a German Shepherd, and his mother a Staffordshire Bull Terrier. He was a former rescue dog adopted by Hattersley from Brent Animal Shelter, in 1995.In 1996, Buster attacked and killed a goose in St. James's Park, London. On 6 April, Hattersley was stopped and questioned by the police while returning home after walking Buster in the park. Buster was suspected of killing the goose, while not under Hattersley's control, and a quick check revealed blood around his muzzle. As the goose was located in a Royal Park, it was the property of The Queen. The Royal connection, coupled with Hattersley's prominent public position, led to national media coverage of the incident. He was charged with contravening Regulation 3(5)(b) of the Royal and Other Parks and Gardens Regulations 1977. On 20 November 1996, Hattersley pleaded guilty by letter, and was fined £25 for letting Buster off the lead (although he claimed that Buster had pulled the lead out of his hand), and £50 for letting him kill the goose."),
        Puppy(R.drawable.catnew, "Kitty", "Female","The American Wirehair is a spontaneous mutation of the American Shorthair. It first occurred as a random mutation among a litter of five born to a pair of barn cats in 1966 in Vernon, in upstate New York. This single red-and-white male had wiry fur. The owner of the cats called a local breeder of Rex cats, Mrs. Joan O'Shea, to take a look at the kitten. She bought the kitten for \$50, along with one of his normal-coated female littermates, to start a breeding program. The wirehaired male was named Council Rock Farms Adams of Hi-Fi ('Adam' for short),and the female Tip-Top."),
        Puppy(R.drawable.dog1, "Hula","Female", "The Shih Tzu is a strong little dog with a small muzzle and normally have large dark brown eyes. They have a soft and long double coat. Although sometimes long, a Shih Tzu will not always have extremely lengthy hair like the Pekingese (but with short legs). Some of them have more short, curly hair. This is purely a choice made by the owners. A Shih Tzu should stand no more than 26.7 cm at the withers and with an ideal weight of 4.0 to 7.5 kg. Floppy ears are covered with long fur, and the heavily furred tail is carried curled over the back. The coat may be of any color, though white and with blazes of grey are frequently seen."),
        Puppy(R.drawable.jack, "Jack", "Male","The American Bully, as it is now known, began development in the 1980s with the majority of the final behavioral and aesthetic product being completed in the 1990’s.[citation needed] There is consensus that at least five other breeds were used to attain the more \"bully\" physical traits desired as well as the more diminutive size of some lines. The American Pit Bull Terrier (APBT) was the foundation (parent breed) used to create the American Bully. The APBT has maintained a characteristic appearance and temperament for over a century.")
    )
}
